(async function(){
  const {$, esc, yen} = GuildUtils;
  const data = await GuildStorage.init();
  const SESSION='otakuba.v3.final.admin.session';
  const tabs=[['dash','📊 概要'],['menu','🍴 メニュー'],['monsters','⚔️ 討伐'],['settings','⚙️ 設定'],['customers','👤 顧客'],['sales','💰 履歴'],['sync','☁️ 同期'],['reset','🧹 reset']];
  let current='dash', customerQuery='', salesQuery='';
  function loginOk(){return sessionStorage.getItem(SESSION)==='ok'} function showLogin(){$('adminLogin').classList.remove('hidden');$('adminApp').classList.add('hidden')} function showApp(){$('adminLogin').classList.add('hidden');$('adminApp').classList.remove('hidden');renderTabs();render()}
  $('adminLoginBtn').onclick=()=>{if($('adminPass').value===(data.settings.adminPassword||'OTAKU')){sessionStorage.setItem(SESSION,'ok');showApp()}else $('loginError').textContent='パスワードが違います'};
  $('adminBackToIndex').onclick=()=>location.href='index.html';$('adminHeaderToIndex').onclick=()=>location.href='index.html';$('logoutBtn').onclick=()=>{sessionStorage.removeItem(SESSION);showLogin()};
  function toast(m){const t=$('toast');t.textContent=m;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),1500)}
  function save(){GuildStorage.save()}
  function renderTabs(){$('adminTabs').innerHTML=tabs.map(t=>`<button class="tab ${current===t[0]?'active':''}" data-tab="${t[0]}">${t[1]}</button>`).join('');document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{current=b.dataset.tab;renderTabs();render()})}
  function cats(){const a=Array.isArray(data.settings.categories)?data.settings.categories:[];return a.length?a:[{id:'food',name:'フード',icon:'🍖'}]}
  function normalizeProduct(p,i){p=p||{};p.id=p.id||GuildUtils.uid('menu');p.cat=p.cat||p.category||'food';p.category=p.cat;p.name=p.name||'商品';p.price=Number(p.price)||0;p.emoji=p.emoji||p.icon||'🍽️';p.icon=p.emoji;p.desc=p.desc||'';p.image=p.image||'';p.hidden=!!p.hidden;p.sort=Number(p.sort||i);return p}
  function renderMenu(){data.menu=(data.menu||[]).map(normalizeProduct);const cs=cats();const opts=cs.map(c=>`<option value="${esc(c.id)}">${esc((c.icon?c.icon+' ':'')+c.name)}</option>`).join('');$('adminContent').innerHTML=`<h2>🍴 メニュー管理</h2><div class="toolbar"><button class="btn gold" id="addProduct">商品追加</button><button class="btn green" id="saveMenu">保存</button><button class="btn" id="openAll">全部開く</button><button class="btn" id="closeAll">全部閉じる</button><button class="btn" id="jsonMode">JSON</button></div><div class="category-list">${cs.map((c,ci)=>{const items=data.menu.map((p,i)=>({p,i})).filter(x=>x.p.cat===c.id);return `<section class="category-block ${ci===0?'open':''}"><button class="category-head"><span>${esc((c.icon?c.icon+' ':'')+c.name)} <b>(${items.length})</b></span><span class="category-toggle">${ci===0?'閉じる':'開く'}</span></button><div class="category-body">${items.length?items.map(({p,i})=>productCard(p,i,opts)).join(''):'<div class="empty">なし</div>'}</div></section>`}).join('')}</div>`;
    document.querySelectorAll('.category-head').forEach(h=>h.onclick=()=>{const b=h.closest('.category-block');b.classList.toggle('open');h.querySelector('.category-toggle').textContent=b.classList.contains('open')?'閉じる':'開く'});document.querySelectorAll('[data-menu-index]').forEach(card=>{const p=data.menu[+card.dataset.menuIndex];card.querySelector('[data-field="cat"]').value=p.cat});document.querySelectorAll('[data-del-product]').forEach(btn=>btn.onclick=()=>{if(confirm('削除しますか？')){data.menu.splice(+btn.dataset.delProduct,1);save();renderMenu()}});$('addProduct').onclick=()=>{saveMenuForm();data.menu.push(normalizeProduct({name:'新商品',cat:cs[0].id},data.menu.length));save();renderMenu()};$('saveMenu').onclick=()=>{saveMenuForm();toast('保存しました')};$('openAll').onclick=()=>toggleCats(true);$('closeAll').onclick=()=>toggleCats(false);$('jsonMode').onclick=()=>textareaEditor('menu','menu.json')}
  function toggleCats(o){document.querySelectorAll('.category-block').forEach(b=>{b.classList.toggle('open',o);b.querySelector('.category-toggle').textContent=o?'閉じる':'開く'})}
  function productCard(p,i,opts){return `<div class="admin-card product-edit-card" data-menu-index="${i}"><div class="admin-card-title">#${i+1} ${esc(p.name)}</div><label>商品名<input data-field="name" value="${esc(p.name)}"></label><label>ジャンル<select data-field="cat">${opts}</select></label><label>価格<input data-field="price" type="number" value="${p.price}"></label><label>絵文字<input data-field="emoji" value="${esc(p.emoji)}"></label><label>画像<input data-field="image" value="${esc(p.image)}"></label><label>説明<textarea data-field="desc">${esc(p.desc)}</textarea></label><label class="check-row"><input data-field="hidden" type="checkbox" ${p.hidden?'checked':''}>非表示</label><button class="btn red small" data-del-product="${i}">削除</button></div>`}
  function saveMenuForm(){document.querySelectorAll('[data-menu-index]').forEach(card=>{const p=data.menu[+card.dataset.menuIndex];p.name=card.querySelector('[data-field="name"]').value;p.cat=card.querySelector('[data-field="cat"]').value;p.category=p.cat;p.price=+card.querySelector('[data-field="price"]').value||0;p.emoji=card.querySelector('[data-field="emoji"]').value||'🍽️';p.icon=p.emoji;p.image=card.querySelector('[data-field="image"]').value;p.desc=card.querySelector('[data-field="desc"]').value;p.hidden=card.querySelector('[data-field="hidden"]').checked});save()}
  function customerListHtml(){const q=customerQuery.toLowerCase();const list=(data.customers||[]).map((c,i)=>({c,i})).filter(({c})=>!q||[c.name,c.title,c.memo,c.id].some(v=>String(v||'').toLowerCase().includes(q)));return list.length?list.map(({c,i})=>customerCard(c,i)).join(''):'<div class="empty">なし</div>';}
  function refreshCustomerList(){const box=$('customerListBox');if(box)box.innerHTML=customerListHtml();bindCustomerListEvents();}
  function bindCustomerListEvents(){document.querySelectorAll('[data-del-customer]').forEach(b=>b.onclick=()=>{if(confirm('削除しますか？')){data.customers.splice(+b.dataset.delCustomer,1);save();refreshCustomerList()}});document.querySelectorAll('[data-sales-of]').forEach(b=>b.onclick=()=>{salesQuery=data.customers[+b.dataset.salesOf].name;current='sales';renderTabs();renderSales()})}
  function renderCustomers(){$('adminContent').innerHTML=`<h2>👤 顧客管理</h2><div class="toolbar searchbar"><input id="customerSearch" placeholder="顧客検索（Enterで検索）" value="${esc(customerQuery)}" enterkeyhint="search"><button class="btn" id="customerSearchBtn">検索</button><button class="btn gold" id="addCustomer">追加</button><button class="btn green" id="saveCustomers">保存</button><button class="btn" id="jsonCustomers">JSON</button></div><div class="customer-list" id="customerListBox">${customerListHtml()}</div>`;const si=$('customerSearch');const run=()=>{customerQuery=si.value;refreshCustomerList()};si.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();run();si.focus()}});$('customerSearchBtn').onclick=()=>{run();si.focus()};$('addCustomer').onclick=()=>{saveCustomerForm();data.customers.unshift({id:GuildUtils.uid('cust'),name:'新規冒険者',level:1,title:'新米冒険者',visits:0,total:0,lastVisit:'',memo:''});save();refreshCustomerList()};$('saveCustomers').onclick=()=>{saveCustomerForm();toast('保存しました')};$('jsonCustomers').onclick=()=>textareaEditor('customers','customers.json');bindCustomerListEvents()}
  function customerCard(c,i){const sales=(data.sales||[]).filter(s=>s.customer===c.name);return `<div class="admin-card customer-card" data-customer-index="${i}"><div class="customer-head"><div class="admin-card-title">👤 ${esc(c.name)}</div><span class="badge">${esc(c.id||'')}</span></div><div class="customer-mini-grid"><label>名前<input data-field="name" value="${esc(c.name||'')}"></label><label>Lv<input data-field="level" type="number" value="${c.level||1}"></label><label>二つ名<input data-field="title" value="${esc(c.title||'')}"></label><label>来店<input data-field="visits" type="number" value="${c.visits||0}"></label><label>累計<input data-field="total" type="number" value="${c.total||0}"></label><label>最終<input data-field="lastVisit" value="${esc(c.lastVisit||'')}"></label></div><label class="wide-label">メモ<textarea data-field="memo">${esc(c.memo||'')}</textarea></label><div class="billbox">履歴 ${sales.length}件</div><div class="toolbar"><button class="btn small" data-sales-of="${i}">履歴を見る</button><button class="btn red small" data-del-customer="${i}">削除</button></div></div>`}
  function saveCustomerForm(){document.querySelectorAll('[data-customer-index]').forEach(card=>{const c=data.customers[+card.dataset.customerIndex];c.name=card.querySelector('[data-field="name"]').value;c.level=+card.querySelector('[data-field="level"]').value||1;c.title=card.querySelector('[data-field="title"]').value;c.visits=+card.querySelector('[data-field="visits"]').value||0;c.total=+card.querySelector('[data-field="total"]').value||0;c.lastVisit=card.querySelector('[data-field="lastVisit"]').value;c.memo=card.querySelector('[data-field="memo"]').value});save()}
  function salesListHtml(){const q=salesQuery.toLowerCase();const list=(data.sales||[]).map((s,i)=>({s,i})).filter(({s})=>!q||[s.customer,s.timeText,s.reason,s.type,(s.items||[]).map(x=>x.name).join(' ')].some(v=>String(v||'').toLowerCase().includes(q))).reverse();return list.length?list.map(({s,i})=>saleCard(s,i)).join(''):'<div class="empty">なし</div>';}
  function refreshSalesList(){const box=$('salesListBox');if(box)box.innerHTML=salesListHtml();bindSalesListEvents();}
  function bindSalesListEvents(){document.querySelectorAll('[data-del-sale]').forEach(b=>b.onclick=()=>{if(confirm('削除しますか？')){data.sales.splice(+b.dataset.delSale,1);save();refreshSalesList()}});document.querySelectorAll('[data-cancel-sale]').forEach(b=>b.onclick=()=>{const s=data.sales[+b.dataset.cancelSale];s.type='cancel';s.reason=(s.reason||'')+' キャンセル';save();refreshSalesList()})}
  function renderSales(){$('adminContent').innerHTML=`<h2>💰 注文・会計履歴</h2><div class="toolbar searchbar"><input id="salesSearch" placeholder="履歴検索（Enterで検索）" value="${esc(salesQuery)}" enterkeyhint="search"><button class="btn" id="salesSearchBtn">検索</button><button class="btn green" id="saveSales">保存</button><button class="btn" id="clearSales">解除</button><button class="btn" id="jsonSales">JSON</button></div><div class="sales-list" id="salesListBox">${salesListHtml()}</div>`;const si=$('salesSearch');const run=()=>{salesQuery=si.value;refreshSalesList()};si.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();run();si.focus()}});$('salesSearchBtn').onclick=()=>{run();si.focus()};$('saveSales').onclick=()=>{saveSalesForm();toast('保存しました')};$('clearSales').onclick=()=>{salesQuery='';renderSales()};$('jsonSales').onclick=()=>textareaEditor('sales','sales.json');bindSalesListEvents()}
  function saleCard(s,i){const items=(s.items||[]).map(it=>`・${esc(it.name)} ×${it.qty||1} = ${yen(it.subtotal||0,data.settings.currency)}`).join('<br>');return `<div class="admin-card sale-card" data-sale-index="${i}"><div class="customer-head"><div class="admin-card-title">${s.type==='cancel'?'❌':'💰'} ${esc(s.customer||'')}</div><span class="badge">${esc(s.type||'checkout')}</span></div><div class="customer-mini-grid"><label>顧客<input data-field="customer" value="${esc(s.customer||'')}"></label><label>種別<select data-field="type"><option value="checkout" ${s.type==='checkout'?'selected':''}>会計</option><option value="order" ${s.type==='order'?'selected':''}>注文</option><option value="cancel" ${s.type==='cancel'?'selected':''}>キャンセル</option></select></label><label>合計<input data-field="total" type="number" value="${s.total||0}"></label><label>人数<input data-field="partyCount" type="number" value="${s.partyCount||1}"></label><label class="wide-label">日時<input data-field="timeText" value="${esc(s.timeText||'')}"></label></div><div class="billbox">${items||'明細なし'}</div><label class="wide-label">メモ<textarea data-field="reason">${esc(s.reason||'')}</textarea></label><div class="toolbar"><button class="btn small" data-cancel-sale="${i}">キャンセル扱い</button><button class="btn red small" data-del-sale="${i}">削除</button></div></div>`}
  function saveSalesForm(){document.querySelectorAll('[data-sale-index]').forEach(card=>{const s=data.sales[+card.dataset.saleIndex];s.customer=card.querySelector('[data-field="customer"]').value;s.type=card.querySelector('[data-field="type"]').value;s.total=+card.querySelector('[data-field="total"]').value||0;s.partyCount=+card.querySelector('[data-field="partyCount"]').value||1;s.timeText=card.querySelector('[data-field="timeText"]').value;s.reason=card.querySelector('[data-field="reason"]').value});save()}
  function textareaEditor(key,label){$('adminContent').innerHTML=`<h2>${label}</h2><textarea class="json-box" id="jsonEdit">${esc(JSON.stringify(data[key],null,2))}</textarea><div class="toolbar"><button class="btn gold" id="saveJson">保存</button><button class="btn" id="formatJson">整形</button></div>`;$('saveJson').onclick=()=>{try{data[key]=JSON.parse($('jsonEdit').value);save();toast('保存しました');render()}catch(e){toast('JSONエラー')}};$('formatJson').onclick=()=>{try{$('jsonEdit').value=JSON.stringify(JSON.parse($('jsonEdit').value),null,2)}catch(e){toast('JSONエラー')}}}
  async function renderSync(){const summary=`GAS URL: ${data.settings.gasUrl||'未設定'}`;$('adminContent').innerHTML=`<h2>☁️ GAS同期</h2><div class="billbox">${esc(summary)}</div><div class="toolbar"><button class="btn gold" id="syncPull">GASから全取得</button><button class="btn green" id="syncPushAll">全データ送信</button></div><div class="toolbar"><button class="btn" id="syncPushMenu">メニューのみ送信</button><button class="btn" id="syncPushMonsters">敵のみ送信</button></div><pre id="syncResult" class="json-box" style="min-height:30dvh"></pre>`;
    $('syncPull').onclick=async()=>{$('syncResult').textContent='取得中...';const ok=await GuildStorage.pullCloud();render();$('syncResult').textContent=ok?'GASから取得して反映しました。\n（この端末の表示も更新済み）':'取得失敗。GAS URLとデプロイを確認してください。'};
    $('syncPushAll').onclick=()=>{GuildStorage.pushCloud();toast('全データを送信しました')};
    $('syncPushMenu').onclick=()=>{GuildNotify.send({action:'menuSave',menu:data.menu});toast('メニュー送信')};
    $('syncPushMonsters').onclick=()=>{GuildNotify.send({action:'monstersSave',monsters:data.monsters});toast('敵送信')}}
  function render(){if(current==='dash'){const total=(data.sales||[]).filter(x=>x.type!=='cancel').reduce((a,x)=>a+(+x.total||0),0);const e=data.monsters[data.currentEnemyIndex]||{};$('adminContent').innerHTML=`<h2>概要</h2><div class="grid"><div class="admin-card"><div class="admin-card-title">現在の敵</div>${esc(e.name||'-')}<br>HP ${e.hp||0}/${e.maxHp||0}</div><div class="admin-card"><div class="admin-card-title">顧客数</div>${data.customers.length}</div><div class="admin-card"><div class="admin-card-title">売上累計</div>${yen(total,data.settings.currency)}</div><div class="admin-card"><div class="admin-card-title">状態</div>v3.0 final</div></div>`} if(current==='menu')renderMenu(); if(current==='monsters')textareaEditor('monsters','monsters.json'); if(current==='settings')textareaEditor('settings','settings.json'); if(current==='customers')renderCustomers(); if(current==='sales')renderSales(); if(current==='sync')renderSync(); if(current==='reset'){$('adminContent').innerHTML=`<h2>リセット</h2><button class="btn red" id="resetProgress">討伐進行を初期化</button>`;$('resetProgress').onclick=()=>{if(confirm('初期化しますか？')){GuildStorage.resetProgress();toast('リセットしました')}}}}
  loginOk()?showApp():showLogin();
})();
