(async function(){
  const {$, esc, yen} = GuildUtils;
  const data = await GuildStorage.init();
  const SESSION='otakuba.v3.final.admin.session';
  const tabs=[['dash','📊 概要'],['menu','🍴 メニュー'],['monsters','⚔️ 討伐'],['settings','⚙️ 設定'],['customers','👤 顧客'],['sales','💰 売上管理'],['sync','☁️ 同期'],['reset','🧹 reset']];
  let current='dash', customerQuery='', salesQuery='';
  function loginOk(){return sessionStorage.getItem(SESSION)==='ok'} function showLogin(){$('adminLogin').classList.remove('hidden');$('adminApp').classList.add('hidden')} function showApp(){$('adminLogin').classList.add('hidden');$('adminApp').classList.remove('hidden');renderTabs();render();startAutoRefresh()}
  let autoTimer=null;
  function startAutoRefresh(){ if(autoTimer)clearInterval(autoTimer); autoTimer=setInterval(async()=>{
    // 概要・顧客・履歴を見ている時だけ自動取得。入力中は邪魔しない
    if(!['dash','customers','sales'].includes(current))return;
    const ae=document.activeElement; if(ae&&(ae.tagName==='INPUT'||ae.tagName==='TEXTAREA'||ae.tagName==='SELECT'))return;
    const ok=await GuildStorage.pullCloud(); if(ok)render();
  }, 10000); }
  $('adminLoginBtn').onclick=()=>{if($('adminPass').value===(data.settings.adminPassword||'OTAKU')){sessionStorage.setItem(SESSION,'ok');showApp()}else $('loginError').textContent='パスワードが違います'};
  $('adminBackToIndex').onclick=()=>location.href='index.html';$('adminHeaderToIndex').onclick=()=>location.href='index.html';$('logoutBtn').onclick=()=>{sessionStorage.removeItem(SESSION);showLogin()};
  function toast(m){const t=$('toast');t.textContent=m;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),1500)}
  function save(){GuildStorage.save()}
  function renderTabs(){$('adminTabs').innerHTML=tabs.map(t=>`<button class="tab ${current===t[0]?'active':''}" data-tab="${t[0]}">${t[1]}</button>`).join('');document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{current=b.dataset.tab;renderTabs();render()})}
  function cats(){const a=Array.isArray(data.settings.categories)?data.settings.categories:[];return a.length?a:[{id:'food',name:'フード',icon:'🍖'}]}
  function normalizeProduct(p,i){p=p||{};p.id=p.id||GuildUtils.uid('menu');p.cat=p.cat||p.category||'food';p.category=p.cat;p.name=p.name||'商品';p.price=Number(p.price)||0;p.emoji=p.emoji||p.icon||'🍽️';p.icon=p.emoji;p.desc=p.desc||'';p.image=p.image||'';p.hidden=!!p.hidden;p.sort=Number(p.sort||i);return p}
  function renderMenu(){data.menu=(data.menu||[]).map(normalizeProduct);const cs=cats();const opts=cs.map(c=>`<option value="${esc(c.id)}">${esc((c.icon?c.icon+' ':'')+c.name)}</option>`).join('');$('adminContent').innerHTML=`<h2>🍴 メニュー管理</h2><div class="toolbar"><button class="btn gold" id="addProduct">商品追加</button><button class="btn green" id="saveMenu">保存</button><button class="btn" id="openAll">全部開く</button><button class="btn" id="closeAll">全部閉じる</button><button class="btn" id="jsonMode">JSON</button></div><div class="category-list">${cs.map((c,ci)=>{const items=data.menu.map((p,i)=>({p,i})).filter(x=>x.p.cat===c.id);return `<section class="category-block ${ci===0?'open':''}"><button class="category-head"><span>${esc((c.icon?c.icon+' ':'')+c.name)} <b>(${items.length})</b></span><span class="category-toggle">${ci===0?'閉じる':'開く'}</span></button><div class="category-body">${items.length?items.map(({p,i})=>productCard(p,i,opts)).join(''):'<div class="empty">なし</div>'}</div></section>`}).join('')}</div>`;
    document.querySelectorAll('.category-head').forEach(h=>h.onclick=()=>{const b=h.closest('.category-block');b.classList.toggle('open');h.querySelector('.category-toggle').textContent=b.classList.contains('open')?'閉じる':'開く'});document.querySelectorAll('[data-menu-index]').forEach(card=>{const p=data.menu[+card.dataset.menuIndex];card.querySelector('[data-field="cat"]').value=p.cat});document.querySelectorAll('[data-del-product]').forEach(btn=>btn.onclick=()=>{if(confirm('削除しますか？')){data.menu.splice(+btn.dataset.delProduct,1);save();renderMenu()}});$('addProduct').onclick=()=>{saveMenuForm();data.menu.push(normalizeProduct({name:'新商品',cat:cs[0].id},data.menu.length));save();renderMenu()};$('saveMenu').onclick=()=>{saveMenuForm();toast('保存しました')};$('openAll').onclick=()=>toggleCats(true);$('closeAll').onclick=()=>toggleCats(false);$('jsonMode').onclick=()=>textareaEditor('menu','menu.json')}
  function toggleCats(o){document.querySelectorAll('.category-block').forEach(b=>{b.classList.toggle('open',o);b.querySelector('.category-toggle').textContent=o?'閉じる':'開く'})}
  function productCard(p,i,opts){return `<div class="admin-card product-edit-card" data-menu-index="${i}"><div class="admin-card-title">#${i+1} ${esc(p.name)}</div><label>商品名<input data-field="name" value="${esc(p.name)}"></label><label>ジャンル<select data-field="cat">${opts}</select></label><label>価格<input data-field="price" type="number" value="${p.price}"></label><label>絵文字<input data-field="emoji" value="${esc(p.emoji)}"></label><label>画像<input data-field="image" value="${esc(p.image)}"></label><label>説明<textarea data-field="desc">${esc(p.desc)}</textarea></label><label class="check-row"><input data-field="hidden" type="checkbox" ${p.hidden?'checked':''}>非表示</label><button class="btn red small" data-del-product="${i}">削除</button></div>`}
  function saveMenuForm(){document.querySelectorAll('[data-menu-index]').forEach(card=>{const p=data.menu[+card.dataset.menuIndex];p.name=card.querySelector('[data-field="name"]').value;p.cat=card.querySelector('[data-field="cat"]').value;p.category=p.cat;p.price=+card.querySelector('[data-field="price"]').value||0;p.emoji=card.querySelector('[data-field="emoji"]').value||'🍽️';p.icon=p.emoji;p.image=card.querySelector('[data-field="image"]').value;p.desc=card.querySelector('[data-field="desc"]').value;p.hidden=card.querySelector('[data-field="hidden"]').checked});save()}
  function customerListHtml(){const q=customerQuery.toLowerCase();const list=(data.customers||[]).map((c,i)=>({c,i})).filter(({c})=>!q||[c.name,c.title,c.memo,c.id].some(v=>String(v||'').toLowerCase().includes(q)));return list.length?list.map(({c,i})=>customerCard(c,i)).join(''):'<div class="empty">なし</div>';}
  function refreshCustomerList(){const box=$('customerListBox');if(box)box.innerHTML=customerListHtml();bindCustomerListEvents();}
  function bindCustomerListEvents(){document.querySelectorAll('[data-del-customer]').forEach(b=>b.onclick=()=>{if(confirm('削除しますか？')){data.customers.splice(+b.dataset.delCustomer,1);save();refreshCustomerList()}});document.querySelectorAll('[data-sales-of]').forEach(b=>b.onclick=()=>{salesQuery=data.customers[+b.dataset.salesOf].name;current='sales';renderTabs();renderSales()})}
  function renderCustomers(){$('adminContent').innerHTML=`<h2>👤 顧客管理</h2><div class="toolbar searchbar"><input id="customerSearch" placeholder="顧客検索（Enterで検索）" value="${esc(customerQuery)}" enterkeyhint="search"><button class="btn" id="customerSearchBtn">検索</button><button class="btn gold" id="addCustomer">追加</button><button class="btn green" id="saveCustomers">保存</button><button class="btn" id="jsonCustomers">JSON</button></div><div class="customer-list" id="customerListBox">${customerListHtml()}</div>`;const si=$('customerSearch');const run=()=>{customerQuery=si.value;refreshCustomerList()};si.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();run();si.focus()}});$('customerSearchBtn').onclick=()=>{run();si.focus()};$('addCustomer').onclick=()=>{saveCustomerForm();data.customers.unshift({id:GuildUtils.uid('cust'),name:'新規冒険者',level:1,title:'新米冒険者',visits:0,total:0,lastVisit:'',memo:''});save();refreshCustomerList()};$('saveCustomers').onclick=()=>{saveCustomerForm();toast('保存しました')};$('jsonCustomers').onclick=()=>textareaEditor('customers','customers.json');bindCustomerListEvents()}
  function customerCard(c,i){const sales=(data.sales||[]).filter(s=>s.customer===c.name);return `<div class="admin-card customer-card" data-customer-index="${i}"><div class="customer-head"><div class="admin-card-title">👤 ${esc(c.name)}</div><span class="badge">${esc(c.id||'')}</span></div><div class="customer-mini-grid"><label>名前<input data-field="name" value="${esc(c.name||'')}"></label><label>Lv<input data-field="level" type="number" value="${c.level||1}"></label><label>二つ名<input data-field="title" value="${esc(c.title||'')}"></label><label>来店<input data-field="visits" type="number" value="${c.visits||0}"></label><label>累計<input data-field="total" type="number" value="${c.total||0}"></label><label>最終<input data-field="lastVisit" value="${esc(c.lastVisit||'')}"></label></div><label class="wide-label">メモ<textarea data-field="memo">${esc(c.memo||'')}</textarea></label><div class="billbox">履歴 ${sales.length}件</div><div class="toolbar"><button class="btn small" data-sales-of="${i}">履歴を見る</button><button class="btn red small" data-del-customer="${i}">削除</button></div></div>`}
  function saveCustomerForm(){document.querySelectorAll('[data-customer-index]').forEach(card=>{const c=data.customers[+card.dataset.customerIndex];c.name=card.querySelector('[data-field="name"]').value;c.level=+card.querySelector('[data-field="level"]').value||1;c.title=card.querySelector('[data-field="title"]').value;c.visits=+card.querySelector('[data-field="visits"]').value||0;c.total=+card.querySelector('[data-field="total"]').value||0;c.lastVisit=card.querySelector('[data-field="lastVisit"]').value;c.memo=card.querySelector('[data-field="memo"]').value});save()}
  function saleDate(s){const raw=s.time||s.timeText||'';const d=raw?new Date(raw):null;return d&&!isNaN(d)?d:null;}
  function saleDay(s){const d=saleDate(s);return d?d.toISOString().slice(0,10):String(s.timeText||'').slice(0,10).replace(/[\/]/g,'-');}
  function monthFromDate(){return new Date().toISOString().slice(0,7)}
  function nextMonth(m){const a=String(m||monthFromDate()).split('-');const d=new Date(Number(a[0]),Number(a[1]||1),1);return d.toISOString().slice(0,7)}
  function salesSettings(){data.salesSettings=data.salesSettings||{currentMonth:monthFromDate(),closedMonths:[]};if(!data.salesSettings.currentMonth)data.salesSettings.currentMonth=monthFromDate();if(!Array.isArray(data.salesSettings.closedMonths))data.salesSettings.closedMonths=[];return data.salesSettings;}
  function saleMonth(s){return s.accountingMonth||String(s.time||saleDay(s)||monthFromDate()).slice(0,7)}
  function activeSales(){return (data.sales||[]).filter(s=>s&&s.type==='checkout');}
  function selectedMonth(){const el=$('salesMonth');return el&&el.value?el.value:salesSettings().currentMonth;}
  function salesInRange(){const m=selectedMonth();return activeSales().filter(s=>saleMonth(s)===m);}
  function sumSales(list){return list.reduce((a,s)=>a+(+s.total||0),0);}
  function todayKey(){return new Date().toISOString().slice(0,10);}
  function rankItems(list,byCat){const map={};list.forEach(s=>(s.items||[]).forEach(it=>{const key=byCat?(it.cat||'未分類'):(it.name||'商品');if(!map[key])map[key]={name:key,qty:0,total:0};map[key].qty+=Number(it.qty||1);map[key].total+=Number(it.subtotal||0);}));return Object.values(map).sort((a,b)=>b.total-a.total).slice(0,20);}
  function chargeTotal(list){let t=0;list.forEach(s=>(s.items||[]).forEach(it=>{if(it.isCharge||it.id==='cover-charge'||it.cat==='charge'||it.name==='席料')t+=Number(it.subtotal||0)}));return t;}
  function salesSummaryHtml(){const ss=salesSettings();const list=salesInRange();const today=activeSales().filter(s=>saleDay(s)===todayKey()&&saleMonth(s)===ss.currentMonth);const total=sumSales(list);const cover=chargeTotal(list);const itemTotal=total-cover;return `<div class="admin-card"><div class="admin-card-title">現在の売上月</div><div class="big-num">${esc(ss.currentMonth)} 月分</div><div class="tiny">清算を押すと次の月へ切り替わります</div></div><div class="grid sales-summary"><div class="admin-card"><div class="admin-card-title">本日売上</div><div class="big-num">${yen(sumSales(today),data.settings.currency)}</div><div class="tiny">会計 ${today.length}件 / 現在月分のみ</div></div><div class="admin-card"><div class="admin-card-title">月締め総額</div><div class="big-num">${yen(total,data.settings.currency)}</div><div class="tiny">${selectedMonth()} 月分 / 会計 ${list.length}件</div></div><div class="admin-card"><div class="admin-card-title">席料合計</div><div class="big-num">${yen(cover,data.settings.currency)}</div><div class="tiny">席料設定 ${yen(data.settings.coverCharge||0,data.settings.currency)} × 人数</div></div><div class="admin-card"><div class="admin-card-title">商品売上</div><div class="big-num">${yen(itemTotal,data.settings.currency)}</div><div class="tiny">総額 − 席料</div></div></div>`;}
  function rankingHtml(){const list=salesInRange();const items=rankItems(list,false);const cats=rankItems(list,true);const row=r=>`<tr><td>${esc(r.name)}</td><td>${r.qty}</td><td>${yen(r.total,data.settings.currency)}</td></tr>`;return `<div class="grid"><div class="admin-card"><div class="admin-card-title">何が何個売れたか</div><table class="sales-table"><thead><tr><th>商品</th><th>個数</th><th>売上</th></tr></thead><tbody>${items.length?items.map(row).join(''):'<tr><td colspan="3">なし</td></tr>'}</tbody></table></div><div class="admin-card"><div class="admin-card-title">内訳</div><table class="sales-table"><thead><tr><th>区分</th><th>数</th><th>売上</th></tr></thead><tbody>${cats.length?cats.map(row).join(''):'<tr><td colspan="3">なし</td></tr>'}</tbody></table></div></div>`;}
  function monthOptions(){const set=new Set([salesSettings().currentMonth]);activeSales().forEach(s=>set.add(saleMonth(s)));return Array.from(set).sort().reverse().map(m=>`<option value="${esc(m)}" ${m===salesSettings().currentMonth?'selected':''}>${esc(m)} 月分</option>`).join('')}
  function salesListHtml(){const q=salesQuery.toLowerCase();const m=selectedMonth();const list=(data.sales||[]).map((s,i)=>({s,i})).filter(({s})=>!s.accountingMonth||saleMonth(s)===m).filter(({s})=>!q||[s.customer,s.timeText,s.reason,s.type,s.accountingMonth,(s.items||[]).map(x=>x.name).join(' ')].some(v=>String(v||'').toLowerCase().includes(q))).reverse();return list.length?list.map(({s,i})=>saleCard(s,i)).join(''):'<div class="empty">なし</div>';}
  function refreshSalesList(){const box=$('salesListBox');if(box)box.innerHTML=salesListHtml();const sum=$('salesSummaryBox');if(sum)sum.innerHTML=salesSummaryHtml()+rankingHtml();bindSalesListEvents();}
  function closeMonth(){const ss=salesSettings();const cur=ss.currentMonth;if(!confirm(cur+' 月分を清算して、次の月に切り替えますか？\n以後の会計は翌月分になります。'))return;if(!ss.closedMonths.includes(cur))ss.closedMonths.push(cur);ss.currentMonth=nextMonth(cur);save();if(GuildStorage.pushCloud)GuildStorage.pushCloud();toast('清算しました。現在月は '+ss.currentMonth+' です');renderSales();}
  function bindSalesListEvents(){document.querySelectorAll('[data-del-sale]').forEach(b=>b.onclick=()=>{if(confirm('削除しますか？')){const s=data.sales[+b.dataset.delSale];if(GuildStorage.markSaleDeleted)GuildStorage.markSaleDeleted(s);data.sales.splice(+b.dataset.delSale,1);save();if(GuildStorage.pushCloud)GuildStorage.pushCloud();refreshSalesList();toast('削除しました')}});document.querySelectorAll('[data-cancel-sale]').forEach(b=>b.onclick=()=>{const s=data.sales[+b.dataset.cancelSale];s.type='cancel';s.reason=(s.reason||'')+' キャンセル';save();refreshSalesList()})}
  function renderSales(){$('adminContent').innerHTML=`<h2>💰 売上管理</h2><div class="toolbar searchbar"><input id="salesSearch" placeholder="履歴検索（Enterで検索）" value="${esc(salesQuery)}" enterkeyhint="search"><button class="btn" id="salesSearchBtn">検索</button><button class="btn" id="clearSales">解除</button></div><div class="toolbar searchbar"><label>売上月<select id="salesMonth">${monthOptions()}</select></label><button class="btn gold" id="applySalesRange">集計更新</button><button class="btn green" id="exportSalesCsv">CSV出力</button><button class="btn red" id="closeSalesMonth">清算して翌月へ</button><button class="btn" id="addManualSale">手入力売上</button><button class="btn" id="jsonSales">JSON</button></div><div id="salesSummaryBox">${salesSummaryHtml()+rankingHtml()}</div><h3>注文履歴から作った売上</h3><div class="toolbar"><button class="btn green" id="saveSales">履歴を保存</button></div><div class="sales-list" id="salesListBox">${salesListHtml()}</div>`;const si=$('salesSearch');const run=()=>{salesQuery=si.value;refreshSalesList()};si.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();run();si.focus()}});$('salesSearchBtn').onclick=()=>{run();si.focus()};$('clearSales').onclick=()=>{salesQuery='';renderSales()};$('applySalesRange').onclick=refreshSalesList;$('salesMonth').onchange=refreshSalesList;$('closeSalesMonth').onclick=closeMonth;$('saveSales').onclick=()=>{saveSalesForm();toast('保存しました');refreshSalesList()};$('jsonSales').onclick=()=>textareaEditor('sales','sales.json');$('exportSalesCsv').onclick=exportCsv;$('addManualSale').onclick=addManualSale;bindSalesListEvents()}
  function addManualSale(){const customer=prompt('顧客名','店頭売上')||'店頭売上';const total=Number(prompt('売上金額','0')||0);if(!total){toast('金額が0です');return;}const rec={id:GuildUtils.uid('sale'),type:'checkout',customer,customerId:'',items:[{id:'manual',name:'手入力売上',cat:'manual',price:total,qty:1,subtotal:total}],total,partyCount:1,time:new Date().toISOString(),timeText:GuildUtils.todayText(),accountingMonth:salesSettings().currentMonth,reason:'管理画面で手入力'};data.sales.push(rec);save();toast('手入力売上を追加しました');renderSales();}
  function exportCsv(){const rows=[['売上月','日時','種別','顧客','人数','商品','数量','小計','合計','メモ']];salesInRange().forEach(s=>{const items=s.items&&s.items.length?s.items:[{name:'',qty:'',subtotal:''}];items.forEach((it,idx)=>rows.push([saleMonth(s),s.timeText||s.time||'',s.type||'',s.customer||'',s.partyCount||'',it.name||'',it.qty||'',it.subtotal||'',idx===0?(s.total||0):'',s.reason||'']));});const csv=rows.map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\n');const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='otakuba_sales_'+selectedMonth()+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
  function saleCard(s,i){const items=(s.items||[]).map(it=>`・${esc(it.name)} ×${it.qty||1} = ${yen(it.subtotal||0,data.settings.currency)}`).join('<br>');return `<div class="admin-card sale-card" data-sale-index="${i}"><div class="customer-head"><div class="admin-card-title">${s.type==='cancel'?'❌':(s.type==='order'?'🧾':'💰')} ${esc(s.customer||'')}</div><span class="badge">${esc(s.accountingMonth||saleMonth(s))} / ${esc(s.type||'checkout')}</span></div><div class="customer-mini-grid"><label>顧客<input data-field="customer" value="${esc(s.customer||'')}"></label><label>種別<select data-field="type"><option value="checkout" ${s.type==='checkout'?'selected':''}>会計</option><option value="order" ${s.type==='order'?'selected':''}>注文</option><option value="cancel" ${s.type==='cancel'?'selected':''}>キャンセル</option></select></label><label>売上月<input data-field="accountingMonth" value="${esc(s.accountingMonth||saleMonth(s))}"></label><label>合計<input data-field="total" type="number" value="${s.total||0}"></label><label>人数<input data-field="partyCount" type="number" value="${s.partyCount||1}"></label><label class="wide-label">日時<input data-field="timeText" value="${esc(s.timeText||'')}"></label></div><div class="billbox">${items||'明細なし'}</div><label class="wide-label">メモ<textarea data-field="reason">${esc(s.reason||'')}</textarea></label><div class="toolbar"><button class="btn small" data-cancel-sale="${i}">キャンセル扱い</button><button class="btn red small" data-del-sale="${i}">削除</button></div></div>`}
  function saveSalesForm(){document.querySelectorAll('[data-sale-index]').forEach(card=>{const s=data.sales[+card.dataset.saleIndex];s.customer=card.querySelector('[data-field="customer"]').value;s.type=card.querySelector('[data-field="type"]').value;s.accountingMonth=card.querySelector('[data-field="accountingMonth"]').value||salesSettings().currentMonth;s.total=+card.querySelector('[data-field="total"]').value||0;s.partyCount=+card.querySelector('[data-field="partyCount"]').value||1;s.timeText=card.querySelector('[data-field="timeText"]').value;s.reason=card.querySelector('[data-field="reason"]').value});save()}
  function textareaEditor(key,label){$('adminContent').innerHTML=`<h2>${label}</h2><textarea class="json-box" id="jsonEdit">${esc(JSON.stringify(data[key],null,2))}</textarea><div class="toolbar"><button class="btn gold" id="saveJson">保存</button><button class="btn" id="formatJson">整形</button></div>`;$('saveJson').onclick=()=>{try{data[key]=JSON.parse($('jsonEdit').value);save();toast('保存しました');render()}catch(e){toast('JSONエラー')}};$('formatJson').onclick=()=>{try{$('jsonEdit').value=JSON.stringify(JSON.parse($('jsonEdit').value),null,2)}catch(e){toast('JSONエラー')}}}

  // ===== 討伐（モンスター）ボタン編集 =====
  var BG_LIST=['grass.png','forest.png','cave.png','mountain.png','ruins.png','volcano.png','castle.png'];
  var IMG_LIST=['slime.png','goblin.png','orc.png','skeleton.png','gargoyle.png','minotaur.png','mimic.png','dragon.png','dark_wizard.png','maou.png'];
  var BGM_LIST=['title','slime','goblin','orc','cave','ruins','maou','ending'];
  function normalizeMonster(m,i){m=m||{};var hpMax=Number(m.maxHp||m.hp||500)||500;m.id=m.id||GuildUtils.uid('enemy');m.name=m.name||('敵'+(i+1));m.stage=m.stage||'草原';m.maxHp=hpMax;m.hp=Number.isFinite(Number(m.hp))?Number(m.hp):hpMax;m.bg=m.bg||m.background||'grass.png';m.background=m.bg;m.image=m.image||'slime.png';m.bgm=m.bgm||'slime';m.sort=Number(m.sort||i);return m;}
  function optList(arr,sel){return arr.map(function(v){return '<option value="'+esc(v)+'"'+(v===sel?' selected':'')+'>'+esc(v)+'</option>';}).join('');}
  function monsterCard(m,i){var thumb=m.image?('<img src="'+esc(m.image)+'" alt="" style="width:48px;height:48px;object-fit:contain;vertical-align:middle;margin-right:8px" onerror="this.style.display=\'none\'">'):'';return '<div class="admin-card" data-monster-index="'+i+'"><div class="admin-card-title">'+thumb+(i+1)+'. '+esc(m.name)+'<br><span style="font-size:.8em;opacity:.7">'+esc(m.stage)+' / HP '+(m.hp||0)+'/'+(m.maxHp||0)+'</span></div>'+
    '<label>敵名<input data-field="name" value="'+esc(m.name)+'"></label>'+
    '<label>ステージ<input data-field="stage" value="'+esc(m.stage)+'"></label>'+
    '<label>BGM<select data-field="bgm">'+optList(BGM_LIST,m.bgm)+'</select></label>'+
    '<label>現在HP<input data-field="hp" type="number" value="'+(m.hp||0)+'"></label>'+
    '<label>最大HP<input data-field="maxHp" type="number" value="'+(m.maxHp||500)+'"></label>'+
    '<label>背景<select data-field="bg">'+optList(BG_LIST,m.bg)+'</select></label>'+
    '<label>敵画像<select data-field="image">'+optList(IMG_LIST,m.image)+'</select></label>'+
    '<div class="enemy-preview" data-preview="'+i+'" style="position:relative;width:100%;height:180px;border:2px solid rgba(255,246,223,.5);border-radius:12px;overflow:hidden;margin:8px 0;background:#000 center/cover no-repeat;background-image:url('+esc(m.bg)+')"><img data-preview-img src="'+esc(m.image)+'" style="position:absolute;left:50%;top:50%;max-width:60%;max-height:80%;object-fit:contain;transform:translate(calc(-50% + '+(Number(m.offsetX)||0)+'%),calc(-50% + '+(Number(m.offsetY)||0)+'%)) scale('+((Number(m.scale)||100)/100)+')" onerror="this.style.display=\'none\'"></div>'+
    '<label>大きさ <span data-scale-val>'+(Number(m.scale)||100)+'</span>%<input data-field="scale" type="range" min="30" max="250" value="'+(Number(m.scale)||100)+'"></label>'+
    '<label>左右 <span data-ox-val>'+(Number(m.offsetX)||0)+'</span>%<input data-field="offsetX" type="range" min="-60" max="60" value="'+(Number(m.offsetX)||0)+'"></label>'+
    '<label>上下 <span data-oy-val>'+(Number(m.offsetY)||0)+'</span>%<input data-field="offsetY" type="range" min="-60" max="60" value="'+(Number(m.offsetY)||0)+'"></label>'+
    '<div class="toolbar"><button class="btn gold small" data-save-monster="'+i+'">この敵を保存</button><button class="btn small" data-current-monster="'+i+'">現在の敵にする</button><button class="btn small" data-dup-monster="'+i+'">複製</button><button class="btn red small" data-del-monster="'+i+'">削除</button></div></div>';}
  function monstersListHtml(){data.monsters=(data.monsters||[]).map(normalizeMonster);return data.monsters.length?data.monsters.map(function(m,i){return monsterCard(m,i);}).join(''):'<div class="empty">なし</div>';}
  function readMonsterCard(card){var m=data.monsters[+card.dataset.monsterIndex];m.name=card.querySelector('[data-field=name]').value;m.stage=card.querySelector('[data-field=stage]').value;m.bgm=card.querySelector('[data-field=bgm]').value;m.hp=+card.querySelector('[data-field=hp]').value||0;m.maxHp=+card.querySelector('[data-field=maxHp]').value||500;m.bg=card.querySelector('[data-field=bg]').value;m.background=m.bg;m.image=card.querySelector('[data-field=image]').value;m.scale=+card.querySelector('[data-field=scale]').value||100;m.offsetX=+card.querySelector('[data-field=offsetX]').value||0;m.offsetY=+card.querySelector('[data-field=offsetY]').value||0;return m;}
  function saveMonsterForm(){document.querySelectorAll('[data-monster-index]').forEach(readMonsterCard);save();}
  function renderMonsters(){$('adminContent').innerHTML='<h2>⚔️ 討伐モンスター管理</h2><div class="toolbar"><button class="btn gold" id="addMonster">追加</button><button class="btn green" id="saveMonsters">全体保存</button><button class="btn" id="jsonMonsters">JSON</button></div><div id="monsterListBox">'+monstersListHtml()+'</div>';bindMonsterEvents();
    $('addMonster').onclick=function(){saveMonsterForm();data.monsters.push(normalizeMonster({name:'新しい敵',maxHp:500},data.monsters.length));save();renderMonsters();};
    $('saveMonsters').onclick=function(){saveMonsterForm();toast('保存しました');if(GuildStorage.pushCloud)GuildStorage.pushCloud();};
    $('jsonMonsters').onclick=function(){textareaEditor('monsters','monsters.json');};}
  function updatePreview(card){var img=card.querySelector('[data-preview-img]');var box=card.querySelector('[data-preview]');if(!img||!box)return;var sc=(+card.querySelector('[data-field=scale]').value||100)/100;var ox=+card.querySelector('[data-field=offsetX]').value||0;var oy=+card.querySelector('[data-field=offsetY]').value||0;var imgSrc=card.querySelector('[data-field=image]').value;var bgSrc=card.querySelector('[data-field=bg]').value;img.src=imgSrc;img.style.display='';box.style.backgroundImage='url('+bgSrc+')';img.style.transform='translate(calc(-50% + '+ox+'%),calc(-50% + '+oy+'%)) scale('+sc+')';var sv=card.querySelector('[data-scale-val]');if(sv)sv.textContent=+card.querySelector('[data-field=scale]').value||100;var oxv=card.querySelector('[data-ox-val]');if(oxv)oxv.textContent=ox;var oyv=card.querySelector('[data-oy-val]');if(oyv)oyv.textContent=oy;}
  function bindMonsterEvents(){
    document.querySelectorAll('[data-monster-index]').forEach(function(card){['scale','offsetX','offsetY'].forEach(function(f){var el=card.querySelector('[data-field='+f+']');if(el)el.addEventListener('input',function(){updatePreview(card);});});var imgSel=card.querySelector('[data-field=image]');if(imgSel)imgSel.addEventListener('change',function(){updatePreview(card);});var bgSel=card.querySelector('[data-field=bg]');if(bgSel)bgSel.addEventListener('change',function(){updatePreview(card);});});
    document.querySelectorAll('[data-save-monster]').forEach(function(b){b.onclick=function(){var card=b.closest('[data-monster-index]');readMonsterCard(card);save();toast('保存しました');if(GuildStorage.pushCloud)GuildStorage.pushCloud();renderMonsters();};});
    document.querySelectorAll('[data-current-monster]').forEach(function(b){b.onclick=function(){saveMonsterForm();data.currentEnemyIndex=+b.dataset.currentMonster;save();toast('現在の敵にしました');if(GuildStorage.pushCloud)GuildStorage.pushCloud();};});
    document.querySelectorAll('[data-dup-monster]').forEach(function(b){b.onclick=function(){saveMonsterForm();var src=data.monsters[+b.dataset.dupMonster];var copy=JSON.parse(JSON.stringify(src));copy.id=GuildUtils.uid('enemy');copy.name=src.name+'（複製）';data.monsters.splice(+b.dataset.dupMonster+1,0,copy);save();renderMonsters();};});
    document.querySelectorAll('[data-del-monster]').forEach(function(b){b.onclick=function(){if(confirm('削除しますか？')){saveMonsterForm();data.monsters.splice(+b.dataset.delMonster,1);save();renderMonsters();}};});}

  // ===== 設定ボタン編集 =====
  function renderSettings(){var s=data.settings;s.notice=Object.assign({enabled:true,title:'本日のお知らせ',body:'',position:'top'},s.notice||{});$('adminContent').innerHTML='<h2>⚙️ 設定</h2><div class="admin-card">'+
    '<label>通貨単位<input id="setCurrency" value="'+esc(s.currency||'G')+'"></label>'+
    '<label>チャージ（1人）<input id="setCover" type="number" value="'+(s.coverCharge??500)+'"></label>'+
    '<label>管理パスワード<input id="setPass" value="'+esc(s.adminPassword||'OTAKU')+'"></label>'+
    '<label class="check-row"><input id="setNotify" type="checkbox" '+(s.notifyOn!==false?'checked':'')+'>通知ON</label>'+
    '<label>GAS URL<input id="setGas" value="'+esc(s.gasUrl||'')+'" placeholder="https://script.google.com/.../exec"></label>'+
    '</div><div class="admin-card notice-admin"><div class="admin-card-title">📢 本日のお知らせ</div>'+
    '<label class="check-row"><input id="noticeEnabled" type="checkbox" '+(s.notice.enabled!==false?'checked':'')+'>一般画面に表示する</label>'+
    '<label>見出し<input id="noticeTitle" value="'+esc(s.notice.title||'本日のお知らせ')+'"></label>'+
    '<label>本文<textarea id="noticeBody" placeholder="例：本日は20時からイベントクエスト開催！">'+esc(s.notice.body||'')+'</textarea></label>'+ 
    '<label>表示位置<select id="noticePosition"><option value="top" '+(s.notice.position!=='bottom'?'selected':'')+'>上に表示</option><option value="bottom" '+(s.notice.position==='bottom'?'selected':'')+'>下に表示</option></select></label>'+ 
    '</div><div class="toolbar"><button class="btn green" id="saveSettings">保存</button><button class="btn" id="jsonSettings">詳細JSON</button></div>';
    $('saveSettings').onclick=function(){s.currency=$('setCurrency').value||'G';s.coverCharge=+$('setCover').value||0;s.adminPassword=$('setPass').value||'OTAKU';s.notifyOn=$('setNotify').checked;s.gasUrl=$('setGas').value.trim();s.notice={enabled:$('noticeEnabled').checked,title:$('noticeTitle').value||'本日のお知らせ',body:$('noticeBody').value||'',position:$('noticePosition').value||'top'};save();toast('保存しました');if(GuildStorage.pushCloud)GuildStorage.pushCloud();};
    $('jsonSettings').onclick=function(){textareaEditor('settings','settings.json');};}
  async function renderSync(){const summary=`GAS URL: ${data.settings.gasUrl||'未設定'}`;$('adminContent').innerHTML=`<h2>☁️ GAS同期</h2><div class="admin-card"><label>GAS URL（/exec で終わるURL）<input id="syncGasUrl" value="${esc(data.settings.gasUrl||'')}" placeholder="https://script.google.com/.../exec"></label><div class="toolbar"><button class="btn gold" id="syncSaveUrl">URLを保存</button><button class="btn" id="syncTest">接続テスト</button></div></div><div class="billbox">${esc(summary)}</div><div class="toolbar"><button class="btn gold" id="syncPull">GASから全取得</button><button class="btn green" id="syncPushAll">全データ送信</button></div><div class="toolbar"><button class="btn" id="syncPushMenu">メニューのみ送信</button><button class="btn" id="syncPushMonsters">敵のみ送信</button></div><pre id="syncResult" class="json-box" style="min-height:24dvh"></pre>`;
    $('syncSaveUrl').onclick=()=>{data.settings.gasUrl=$('syncGasUrl').value.trim();save();toast('GAS URLを保存しました');renderSync();};
    $('syncTest').onclick=async()=>{const url=$('syncGasUrl').value.trim();if(!url){$('syncResult').textContent='URLを入力してください';return;}data.settings.gasUrl=url;save();$('syncResult').textContent='接続テスト中...';try{const res=await fetch(url+(url.includes('?')?'&':'?')+'action=ping&v='+Date.now(),{cache:'no-store'});const j=await res.json();$('syncResult').textContent=j&&j.ok?'✅ 接続成功！GASとつながっています。\n'+JSON.stringify(j):'⚠️ 応答が想定外です:\n'+JSON.stringify(j);}catch(e){$('syncResult').textContent='❌ 接続失敗。URLが正しいか、デプロイのアクセス権が「全員」か確認してください。\n'+String(e);}};
    $('syncPull').onclick=async()=>{$('syncResult').textContent='取得中...';const ok=await GuildStorage.pullCloud();render();$('syncResult').textContent=ok?'GASから取得して反映しました。\n（この端末の表示も更新済み）':'取得失敗。GAS URLとデプロイを確認してください。'};
    $('syncPushAll').onclick=()=>{GuildStorage.pushCloud();toast('全データを送信しました')};
    $('syncPushMenu').onclick=()=>{GuildNotify.send({action:'menuSave',menu:data.menu});toast('メニュー送信')};
    $('syncPushMonsters').onclick=()=>{GuildNotify.send({action:'monstersSave',monsters:data.monsters});toast('敵送信')}}
  function render(){if(current==='dash'){const total=(data.sales||[]).filter(x=>x.type!=='cancel').reduce((a,x)=>a+(+x.total||0),0);const e=data.monsters[data.currentEnemyIndex]||{};$('adminContent').innerHTML=`<h2>概要</h2><div class="grid"><div class="admin-card"><div class="admin-card-title">現在の敵</div>${esc(e.name||'-')}<br>HP ${e.hp||0}/${e.maxHp||0}</div><div class="admin-card"><div class="admin-card-title">顧客数</div>${data.customers.length}</div><div class="admin-card"><div class="admin-card-title">売上累計</div>${yen(total,data.settings.currency)}</div><div class="admin-card"><div class="admin-card-title">状態</div>v3.0 final</div></div>`} if(current==='menu')renderMenu(); if(current==='monsters')renderMonsters(); if(current==='settings')renderSettings(); if(current==='customers')renderCustomers(); if(current==='sales')renderSales(); if(current==='sync')renderSync(); if(current==='reset'){$('adminContent').innerHTML=`<h2>リセット</h2><button class="btn red" id="resetProgress">討伐進行を初期化</button>`;$('resetProgress').onclick=()=>{if(confirm('初期化しますか？')){GuildStorage.resetProgress();toast('リセットしました')}}}}
  loginOk()?showApp():showLogin();
})();
