window.GuildOrder = (() => {
  const {$, yen, todayText} = GuildUtils;
  let pending=null;
  function itemFromProduct(p, qty=1){ const price=Number(p.price)||0; return {id:p.id,name:p.name,cat:p.cat||p.category||'food',price,qty:Number(qty)||1,subtotal:price*(Number(qty)||1)}; }
  function askOrder(product, qty=1){ pending=itemFromProduct(product, qty); const data=GuildStorage.getData(); GuildAudio.playSe('add'); $('orderConfirmBody').textContent=`このクエストを受注しますか？\n\n・${pending.name} ×${pending.qty} = ${yen(pending.subtotal,data.settings.currency)}\n\n注文確定で敵にダメージが入ります。`; GuildUI.openModal('modalOrderConfirm'); }
  function addToBill(item){ const data=GuildStorage.getData(); data.activeBill=data.activeBill||[]; const old=data.activeBill.find(x=>x.id===item.id && !x.isCharge); if(old){old.qty+=item.qty;old.subtotal+=item.subtotal;}else data.activeBill.push(Object.assign({},item)); GuildStorage.save(); }
  function currentSalesMonth(){ const data=GuildStorage.getData(); data.salesSettings=data.salesSettings||{}; if(!data.salesSettings.currentMonth)data.salesSettings.currentMonth=new Date().toISOString().slice(0,7); return data.salesSettings.currentMonth; }
  function withCoverCharge(items){ const data=GuildStorage.getData(); const list=(items||[]).slice(); const cover=Number(data.settings&&data.settings.coverCharge)||0; const party=Math.max(1,Number(data.partyCount||1)||1); if(cover>0){ list.unshift({id:'cover-charge',name:'席料',cat:'charge',price:cover,qty:party,subtotal:cover*party,isCharge:true}); } return list; }
  function record(type, items, total, reason=''){ const data=GuildStorage.getData(); const c=GuildCustomer.current()||{name:'未登録',level:1,title:'',id:''}; const rec={id:GuildUtils.uid(type==='checkout'?'sale':'order'),type,customer:c.name,customerId:c.id||'',items,total,partyCount:data.partyCount||1,time:new Date().toISOString(),timeText:todayText(),reason}; if(type==='checkout'){ rec.accountingMonth=currentSalesMonth(); data.sales.push(rec); c.total=(Number(c.total)||0)+Number(total||0); c.lastVisit=rec.timeText; GuildStorage.save(); } return rec; }
  function payload(type,sale,items,total,extra={}){ const data=GuildStorage.getData(); const c=GuildCustomer.current(); const e=GuildBattle.enemy(); return Object.assign({action:type,type,orderId:sale.id,sale,adventurerId:c&&c.id||'',adventurer:c&&c.name||sale.customer||'未登録',name:c&&c.name||sale.customer||'未登録',title:c&&c.title||'',level:c&&c.level||1,visits:c&&c.visits||0,partyCount:data.partyCount||1,items,total,enemy:e?{name:e.name,hp:e.hp,maxHp:e.maxHp,defeated:false}:null,source:'index',appVersion:GuildApp.VERSION,time:todayText()},extra); }
  async function confirmOrder(){ if($('screenMain').classList.contains('combat-lock'))return; if(!pending){GuildUI.toast('注文がありません');return;} const item=Object.assign({},pending); pending=null; $('btnDoOrder').disabled=true; const sale=record('order',[item],item.subtotal); addToBill(item); GuildNotify.send(payload('order',sale,[item],item.subtotal,{orderDamage:item.subtotal,directOrder:true})); if(GuildStorage.pushCloud)GuildStorage.pushCloud(); GuildUI.closeModals(); GuildUI.show('screenMain'); await GuildBattle.applyDamage(item.subtotal,(defeated,finalDefeated)=>{GuildStorage.save();GuildBattle.render();$('screenMain').classList.remove('combat-lock');$('damagePop').classList.remove('on');$('btnDoOrder').disabled=false;GuildUI.toast(finalDefeated?'魔王を討伐した！':(defeated?'撃破！ 注文完了':'注文完了！'));}); }
  function checkoutAsk(){ const data=GuildStorage.getData(); const base=(data.activeBill||[]).slice(); const all=withCoverCharge(base); const total=all.reduce((s,i)=>s+Number(i.subtotal||0),0); $('checkoutConfirmBody').textContent=all.length?`帰還しますか？\n\n${all.map(i=>`・${i.name} ×${Number(i.qty||1)} = ${yen(i.subtotal,data.settings.currency)}`).join('\n')}\n\n会計合計 ${yen(total,data.settings.currency)}\n売上月 ${currentSalesMonth()} 月分\n\n会計のみ行います。ダメージは注文確定時に入ります。`:'未会計の注文はありません。帰還しますか？'; GuildUI.openModal('modalCheckoutConfirm'); }
  function checkoutDo(){ const data=GuildStorage.getData(); const all=withCoverCharge((data.activeBill||[]).slice()); const total=all.reduce((s,i)=>s+Number(i.subtotal||0),0); const c=GuildCustomer.current(); const oldLevel=c?Number(c.level||1):1; const sale=record('checkout',all,total); GuildNotify.send(payload('checkout',sale,all,total,{checkoutOnly:true})); if(GuildStorage.pushCloud)GuildStorage.pushCloud(); const lv=GuildCustomer.levelUpByTotal(); if(lv.leveled){GuildAudio.playSe('levelup'); if(window.GuildApp&&GuildApp.showLevelUp) GuildApp.showLevelUp(oldLevel,lv.newLevel);} data.activeBill=[]; GuildStorage.save(); GuildBattle.render(); GuildUI.closeModals(); $('screenMain').classList.remove('combat-lock'); GuildUI.toast('おかえりなさい。クエスト達成（会計）を送信しました'); setTimeout(()=>{ if(window.GuildApp&&GuildApp.showWelcomeBack) GuildApp.showWelcomeBack(); else GuildUI.show('screenWelcome'); }, lv.leveled?1800:900); }
  function cancelPending(){ pending=null; GuildAudio.playSe('cancel'); GuildUI.closeModals(); }
  return {askOrder, confirmOrder, checkoutAsk, checkoutDo, cancelPending, record};
})();
